apiVersion: v1
kind: Service
metadata:
  name: demo-policy-pipeline_dev
  labels:
    app: demo-policy-pipeline
    lifecycle: dev
  namespace: myapp-dev
spec:
  ports:
    - port: 80
  selector:
    app: demo-policy-pipeline
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-policy-pipeline_dev
  namespace: myapp-dev
spec:
  selector:
    matchLabels:
      app: demo-policy-pipeline
      lifecycle: dev
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-policy-pipeline
        lifecycle: dev
    spec:
      containers:
        - name: demo-policy-pipeline
          image: gcr.io/google-samples/node-hello:1.0
          ports:
            - containerPort: 1323
              protocol: TCP